using System.Net.Http.Json;
using ISOTankApp.Models;

namespace ISOTankApp.Views;

public partial class ReviewSubmitPage : ContentPage
{
    private readonly HttpClient _httpClient;

    public ReviewSubmitPage()
    {
        InitializeComponent();
        _httpClient = new HttpClient
        {
            BaseAddress = new Uri("https://uat.spairyx.com/itankapi/")
        };
    }

    protected override void OnAppearing()
    {
        base.OnAppearing();
        LoadSummaryData();
        
        SubmitButton.Text = SessionManager.InspectionId.HasValue 
            ? "UPDATE FINAL REPORT" 
            : "SUBMIT FINAL REPORT";
    }

    private void LoadSummaryData()
    {
        // General Info
        if (SessionManager.SelectedTank != null)
        {
            RevTankNumber.Text = SessionManager.SelectedTank.Name;
            RevPressure.Text = SessionManager.SelectedTank.WorkingPressure + " BAR";
            RevTemp.Text = SessionManager.SelectedTank.Temp;
            RevFrame.Text = SessionManager.SelectedTank.Frame;
            RevCabinet.Text = SessionManager.SelectedTank.Cabinet;
            RevNextInspection.Text = SessionManager.SelectedTank.NextInspectionDue;
        }

        RevStatus.Text = string.IsNullOrEmpty(SessionManager.SelectedTankStatus) ? "N/A" : SessionManager.SelectedTankStatus;
        RevLocation.Text = string.IsNullOrEmpty(SessionManager.SelectedLocation) ? "N/A" : SessionManager.SelectedLocation;
        
        // Generate mock report number based on date and tank
        RevDate.Text = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
        RevReportNumber.Text = SessionManager.InspectionId.HasValue ? "Existing Report" : "Auto-Generated by Server";

        // Checklist
        if (SessionManager.ChecklistState != null)
        {
            RevChecklistCollectionView.ItemsSource = SessionManager.ChecklistState;
        }

        // Photos
        if (SessionManager.UploadedPhotos != null)
        {
            // Only show photos that have an actual image path
            var validPhotos = SessionManager.UploadedPhotos.Where(p => !string.IsNullOrEmpty(p.ImagePath)).ToList();
            BindableLayout.SetItemsSource(RevPhotosFlexLayout, validPhotos);
        }
    }

    private async void OnSubmitTapped(object sender, EventArgs e)
    {
        bool isConfirmed = await DisplayAlert(
            "Confirm Submission", 
            "Are you sure you want to submit this inspection?", 
            "Yes", 
            "Cancel");

        if (!isConfirmed)
            return;

        try
        {
            // Prepare full payload
            var payload = new 
            {
                BasicInfo = new InspectionBasicInfo
                {
                    Id = SessionManager.InspectionId ?? 0,
                    TankNumber = SessionManager.SelectedTank?.Name ?? "",
                    FrameType = SessionManager.SelectedTank?.Frame ?? "",
                    CabinetType = SessionManager.SelectedTank?.Cabinet ?? "",
                    Manufacturer = SessionManager.SelectedTank?.MfgrName ?? "",
                    VacuumReading = SessionManager.VacuumReading ?? "",
                    Notes = "Submitted from MAUI",
                    StatusId = SessionManager.SelectedTankStatusId,
                    InspectionTypeId = SessionManager.SelectedInspectionTypeId,
                    LocationId = SessionManager.SelectedLocationId,
                    SafetyValveBrandId = SessionManager.SelectedSafetyValveId
                },
                ChecklistItems = SessionManager.ChecklistState?.SelectMany(g => g.Items).Select(i => new
                {
                    SubJobId = i.SubJobId,
                    IsFaulty = i.IsFaulty,
                    Comment = i.Comment,
                    AssignedPhotoKeys = i.AssignedPhotoKeys.ToList()
                }).ToList() ?? new(),
                Photos = SessionManager.UploadedPhotos?.Where(p => p.HasImage).Select(p => new
                {
                    CategoryKey = p.Category.Key,
                    ImagePath = p.ImagePath,
                    IsMarked = p.IsMarked
                }).ToList() ?? new()
            };

            // Call the full submit endpoint
            var response = await _httpClient.PostAsJsonAsync("api/inspection/submit-full", payload);
            
            if (response.IsSuccessStatusCode)
            {
                await DisplayAlert("Success", "Inspection report successfully submitted!", "OK");
                
                // Reset Session & return to start
                SessionManager.Clear();
                GlobalState.IsPhotosSaved = false;
                GlobalState.IsChecklistSaved = false;
                
                await Navigation.PopToRootAsync();
            }
            else
            {
                var error = await response.Content.ReadAsStringAsync();
                await DisplayAlert("Submit Error", $"Failed to submit report: {response.StatusCode}\n{error}", "OK");
            }
        }
        catch (Exception ex)
        {
            await DisplayAlert("Error", $"An error occurred: {ex.Message}", "OK");
        }
        finally
        {
            // LoadingSpinner.IsVisible = false;
        }
    }

    private async void OnCancelTapped(object sender, EventArgs e)
    {
        await Navigation.PopAsync();
    }

    private async void OnTankInfoTapped(object sender, EventArgs e)
    {
        await Navigation.PopToRootAsync();
    }

    private async void OnUploadPhotosTapped(object sender, EventArgs e)
    {
        // Go back to Upload Photos by popping pages until we hit it, or pop twice
        // In MAUI, the stack is: TankInfo -> UploadPhotos -> Checklist -> Review
        var stack = Navigation.NavigationStack;
        var uploadPhotosPage = stack.FirstOrDefault(p => p is UploadPhotosPage);
        if (uploadPhotosPage != null)
        {
            // We can't pop to an arbitrary page easily without PopToAsync which doesn't exist,
            // so we'll pop to root then push UploadPhotos, OR remove intermediate pages and pop.
            // A simpler way: pop twice, assuming stack is exactly TankInfo -> Upload -> Checklist -> Review
            Navigation.RemovePage(stack[stack.Count - 2]); // Remove Checklist
            await Navigation.PopAsync(); // This will pop Review and show UploadPhotos
        }
    }

    private async void OnChecklistTapped(object sender, EventArgs e)
    {
        await Navigation.PopAsync();
    }
}
